### ISSUE TITLE
[Chore][Next.js] Configure a code Linter

### ISSUE THREAD

**Issue by malparty** [huy1010/back-end#14]
## Issue

The code in the Next.js application is often hard to read (mainly due to some missing empty lines) or cluttered with unused variables/imports. 

## Expected

Next.js provides an [ESLint integration](https://nextjs.org/docs/app/building-your-application/configuring/eslint) and is quite straightforward to setup. This allows keeping the code lint without spending too much time on it.

**Comment by huy1010** [comment]
I already set up Linter for NextJS project, please help me check it out.

**Comment by malparty** [comment]
Thanks, that PR makes everything cleaner ✨
